Traceback (most recent call last):
  File "/Users/keshavsharma/Desktop/UI_Auto/Selenium_Operations/Waits_Operations.py", line 31, in wait_until_element_present
    element_present = wait.until(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x000000010052bfa8 chromedriver + 4886440
1   chromedriver                        0x00000001004a9643 chromedriver + 4351555
2   chromedriver                        0x00000001000f7b27 chromedriver + 477991
3   chromedriver                        0x000000010013c76c chromedriver + 759660
4   chromedriver                        0x000000010013c9c1 chromedriver + 760257
5   chromedriver                        0x0000000100180204 chromedriver + 1036804
6   chromedriver                        0x00000001001625fd chromedriver + 914941
7   chromedriver                        0x000000010017d5fe chromedriver + 1025534
8   chromedriver                        0x00000001001623a3 chromedriver + 914339
9   chromedriver                        0x000000010012c57f chromedriver + 693631
10  chromedriver                        0x000000010012db1e chromedriver + 699166
11  chromedriver                        0x00000001004f8b9e chromedriver + 4676510
12  chromedriver                        0x00000001004fd91e chromedriver + 4696350
13  chromedriver                        0x000000010050519f chromedriver + 4727199
14  chromedriver                        0x00000001004fe81a chromedriver + 4700186
15  chromedriver                        0x00000001004d1a62 chromedriver + 4516450
16  chromedriver                        0x000000010051d8c8 chromedriver + 4827336
17  chromedriver                        0x000000010051da45 chromedriver + 4827717
18  chromedriver                        0x00000001005337ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff802303259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8022fec7b thread_start + 15

Traceback (most recent call last):
  File "/Users/keshavsharma/Desktop/UI_Auto/Selenium_Operations/Element_Operations.py", line 27, in find_element
    web_element = self.driver.find_element(self.get_locator_signature(locator), self.get_locator_values(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//i[@class='eicon-close']"}
  (Session info: headless chrome=109.0.5414.87)
Stacktrace:
0   chromedriver                        0x000000010052bfa8 chromedriver + 4886440
1   chromedriver                        0x00000001004a9643 chromedriver + 4351555
2   chromedriver                        0x00000001000f7b27 chromedriver + 477991
3   chromedriver                        0x000000010013c76c chromedriver + 759660
4   chromedriver                        0x000000010013c9c1 chromedriver + 760257
5   chromedriver                        0x0000000100180204 chromedriver + 1036804
6   chromedriver                        0x00000001001625fd chromedriver + 914941
7   chromedriver                        0x000000010017d5fe chromedriver + 1025534
8   chromedriver                        0x00000001001623a3 chromedriver + 914339
9   chromedriver                        0x000000010012c57f chromedriver + 693631
10  chromedriver                        0x000000010012db1e chromedriver + 699166
11  chromedriver                        0x00000001004f8b9e chromedriver + 4676510
12  chromedriver                        0x00000001004fd91e chromedriver + 4696350
13  chromedriver                        0x000000010050519f chromedriver + 4727199
14  chromedriver                        0x00000001004fe81a chromedriver + 4700186
15  chromedriver                        0x00000001004d1a62 chromedriver + 4516450
16  chromedriver                        0x000000010051d8c8 chromedriver + 4827336
17  chromedriver                        0x000000010051da45 chromedriver + 4827717
18  chromedriver                        0x00000001005337ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff802303259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8022fec7b thread_start + 15

Traceback (most recent call last):
  File "/Users/keshavsharma/Desktop/UI_Auto/Selenium_Operations/Element_Operations.py", line 27, in find_element
    web_element = self.driver.find_element(self.get_locator_signature(locator), self.get_locator_values(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//i[@class='eicon-close']"}
  (Session info: headless chrome=109.0.5414.87)
Stacktrace:
0   chromedriver                        0x000000010052bfa8 chromedriver + 4886440
1   chromedriver                        0x00000001004a9643 chromedriver + 4351555
2   chromedriver                        0x00000001000f7b27 chromedriver + 477991
3   chromedriver                        0x000000010013c76c chromedriver + 759660
4   chromedriver                        0x000000010013c9c1 chromedriver + 760257
5   chromedriver                        0x0000000100180204 chromedriver + 1036804
6   chromedriver                        0x00000001001625fd chromedriver + 914941
7   chromedriver                        0x000000010017d5fe chromedriver + 1025534
8   chromedriver                        0x00000001001623a3 chromedriver + 914339
9   chromedriver                        0x000000010012c57f chromedriver + 693631
10  chromedriver                        0x000000010012db1e chromedriver + 699166
11  chromedriver                        0x00000001004f8b9e chromedriver + 4676510
12  chromedriver                        0x00000001004fd91e chromedriver + 4696350
13  chromedriver                        0x000000010050519f chromedriver + 4727199
14  chromedriver                        0x00000001004fe81a chromedriver + 4700186
15  chromedriver                        0x00000001004d1a62 chromedriver + 4516450
16  chromedriver                        0x000000010051d8c8 chromedriver + 4827336
17  chromedriver                        0x000000010051da45 chromedriver + 4827717
18  chromedriver                        0x00000001005337ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff802303259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8022fec7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/keshavsharma/Desktop/UI_Auto/Selenium_Operations/Element_Operations.py", line 55, in click
    ele = self.find_element(locator)
  File "/Users/keshavsharma/Desktop/UI_Auto/Selenium_Operations/Element_Operations.py", line 35, in find_element
    assert False
AssertionError
