Traceback (most recent call last):
  File "/Users/keshavsharma/Desktop/UI_Auto/Selenium_Operations/Waits_Operations.py", line 31, in wait_until_element_present
    element_present = wait.until(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000105160fa8 chromedriver + 4886440
1   chromedriver                        0x00000001050de643 chromedriver + 4351555
2   chromedriver                        0x0000000104d2cb27 chromedriver + 477991
3   chromedriver                        0x0000000104d7176c chromedriver + 759660
4   chromedriver                        0x0000000104d719c1 chromedriver + 760257
5   chromedriver                        0x0000000104db5204 chromedriver + 1036804
6   chromedriver                        0x0000000104d975fd chromedriver + 914941
7   chromedriver                        0x0000000104db25fe chromedriver + 1025534
8   chromedriver                        0x0000000104d973a3 chromedriver + 914339
9   chromedriver                        0x0000000104d6157f chromedriver + 693631
10  chromedriver                        0x0000000104d62b1e chromedriver + 699166
11  chromedriver                        0x000000010512db9e chromedriver + 4676510
12  chromedriver                        0x000000010513291e chromedriver + 4696350
13  chromedriver                        0x000000010513a19f chromedriver + 4727199
14  chromedriver                        0x000000010513381a chromedriver + 4700186
15  chromedriver                        0x0000000105106a62 chromedriver + 4516450
16  chromedriver                        0x00000001051528c8 chromedriver + 4827336
17  chromedriver                        0x0000000105152a45 chromedriver + 4827717
18  chromedriver                        0x00000001051687ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff802303259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8022fec7b thread_start + 15

Traceback (most recent call last):
  File "/Users/keshavsharma/Desktop/UI_Auto/Selenium_Operations/Element_Operations.py", line 27, in find_element
    web_element = self.driver.find_element(self.get_locator_signature(locator), self.get_locator_values(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//i[@class='eicon-close']"}
  (Session info: chrome=109.0.5414.87)
Stacktrace:
0   chromedriver                        0x0000000105160fa8 chromedriver + 4886440
1   chromedriver                        0x00000001050de643 chromedriver + 4351555
2   chromedriver                        0x0000000104d2cb27 chromedriver + 477991
3   chromedriver                        0x0000000104d7176c chromedriver + 759660
4   chromedriver                        0x0000000104d719c1 chromedriver + 760257
5   chromedriver                        0x0000000104db5204 chromedriver + 1036804
6   chromedriver                        0x0000000104d975fd chromedriver + 914941
7   chromedriver                        0x0000000104db25fe chromedriver + 1025534
8   chromedriver                        0x0000000104d973a3 chromedriver + 914339
9   chromedriver                        0x0000000104d6157f chromedriver + 693631
10  chromedriver                        0x0000000104d62b1e chromedriver + 699166
11  chromedriver                        0x000000010512db9e chromedriver + 4676510
12  chromedriver                        0x000000010513291e chromedriver + 4696350
13  chromedriver                        0x000000010513a19f chromedriver + 4727199
14  chromedriver                        0x000000010513381a chromedriver + 4700186
15  chromedriver                        0x0000000105106a62 chromedriver + 4516450
16  chromedriver                        0x00000001051528c8 chromedriver + 4827336
17  chromedriver                        0x0000000105152a45 chromedriver + 4827717
18  chromedriver                        0x00000001051687ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff802303259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8022fec7b thread_start + 15

Traceback (most recent call last):
  File "/Users/keshavsharma/Desktop/UI_Auto/Selenium_Operations/Element_Operations.py", line 27, in find_element
    web_element = self.driver.find_element(self.get_locator_signature(locator), self.get_locator_values(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//i[@class='eicon-close']"}
  (Session info: chrome=109.0.5414.87)
Stacktrace:
0   chromedriver                        0x0000000105160fa8 chromedriver + 4886440
1   chromedriver                        0x00000001050de643 chromedriver + 4351555
2   chromedriver                        0x0000000104d2cb27 chromedriver + 477991
3   chromedriver                        0x0000000104d7176c chromedriver + 759660
4   chromedriver                        0x0000000104d719c1 chromedriver + 760257
5   chromedriver                        0x0000000104db5204 chromedriver + 1036804
6   chromedriver                        0x0000000104d975fd chromedriver + 914941
7   chromedriver                        0x0000000104db25fe chromedriver + 1025534
8   chromedriver                        0x0000000104d973a3 chromedriver + 914339
9   chromedriver                        0x0000000104d6157f chromedriver + 693631
10  chromedriver                        0x0000000104d62b1e chromedriver + 699166
11  chromedriver                        0x000000010512db9e chromedriver + 4676510
12  chromedriver                        0x000000010513291e chromedriver + 4696350
13  chromedriver                        0x000000010513a19f chromedriver + 4727199
14  chromedriver                        0x000000010513381a chromedriver + 4700186
15  chromedriver                        0x0000000105106a62 chromedriver + 4516450
16  chromedriver                        0x00000001051528c8 chromedriver + 4827336
17  chromedriver                        0x0000000105152a45 chromedriver + 4827717
18  chromedriver                        0x00000001051687ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff802303259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8022fec7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/keshavsharma/Desktop/UI_Auto/Selenium_Operations/Element_Operations.py", line 55, in click
    ele = self.find_element(locator)
  File "/Users/keshavsharma/Desktop/UI_Auto/Selenium_Operations/Element_Operations.py", line 35, in find_element
    assert False
AssertionError
